---

# TODO need strategy where to store defaults - which an be overriden by repo vars

name: Github Release Information
description: Fetch and convert data from github to use for a release trigger

branding:
  icon: plus
  color: green

inputs:
  repo:
    description: Repository to query data from in the format of <owner>/<repo-name>
    required: true
  date:
    description: Starting date to start query from.
    required: true
  query_parameters:
    description: Parameters to query for in pr Information
    required: true

outputs:
  raw-output:
    description: Full output json dictionary from github api.
    value: ${{ steps.raw-output.outputs.raw_output }}
  label-list:
    description: List of unique labels found in PRs.
    value: ${{ steps.get-labels-list.outputs.label_list }}
  bump-increment:
    description: Increment for version bumping - either `patch` or 'minor'
    value: ${{ steps.bump-increment.outputs.increment }}
  changelog-markdown:
    description: String containing full makrdown syntax for release changelog information
    value: ${{ steps.write-changelog.outputs.changelog }}

runs:
  using: composite

  steps:
    - name: Get raw GitHub output
      id: raw-output
      shell: bash
      run: |
        raw_output=$(gh pr list --state merged --search 'merged:>=${{ inputs.date }}' --json ${{ inputs.query_parameters }} --repo ${{ inputs.repo }})
        if [[ "$raw_output" == '[]' ]]; then
          echo "raw_output=''" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "raw_output=$raw_output" >> $GITHUB_OUTPUT

    - name: Get label list
      id: get-labels-list
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        label_list=$(python -c 'import fetch_github_data; print(fetch_github_data.get_labels(fetch_github_data.parse_args()))'  "${{ inputs.repo }}" "${{ inputs.query_parameters }}" "${{ inputs.date }}")
        if [[ "$label_list" == '[]' ]]; then
          echo "label_list=''" >> $GITHUB_OUTPUT
          exit 0
        fi

        echo "label_list=$label_list" >> $GITHUB_OUTPUT

    - name: Get bump increment
      id: bump-increment
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        increment=$(python -c 'import fetch_github_data; print(fetch_github_data.get_version_increment())' "${{ inputs.repo }}" "${{ inputs.query_parameters }}" "${{ inputs.date }}")
        echo "increment=$increment" >> $GITHUB_OUTPUT

    - name: Prepare Changelog
      id: write-changelog
      shell: bash
      run: |
        cd $GITHUB_ACTION_PATH
        changelog=$(python -c 'import fetch_github_data; print(fetch_github_data.prepare_changelog_markdown())' "${{ inputs.repo }}" "${{ inputs.query_parameters }}" "${{ inputs.date }}")
        oneline_changelog=$(echo "$changelog" | base64)
        echo "oneline changelog: $oneline_changelog"
        echo "changelog=$oneline_changelog" >> $GITHUB_OUTPUT

...
