name: Test custom action
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CI_TOKEN}}
jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
        - name: test custom action
          id: test-action
          uses: ynput/github-data@main
          with:
            repo: "ynput/ayon-addon-action-testing"
            date: "2024-01-08T09:48:33Z"
            query_parameters: "body,labels,title"