name: Test custom action
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CI_TOKEN }}
jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
        - name: Run action
          id: test-action
          uses: ynput/github-data@main
          with:
            repo: "ynput/ayon-addon-action-testing"
            date: "2024-08-20T12:03:23Z"
            query_parameters: "body,labels,title"

        - name: Test empty pr output
          if: ${{ steps.test-action.outputs.raw-output }}
          run: |
            echo "::error:: Found value: ${{ steps.test-action.outputs.raw-output }}, expected empty value"
            exit 1

        - name: Test empty pr output
          if: ${{ steps.test-action.outputs.label-list }}
          run: |
            echo "::error:: Found value: ${{ steps.test-action.outputs.label-list }}, expected empty value"
            exit 1
