name: Test custom action
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.CI_TOKEN }}
jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
        - name: Run action
          id: test-action
          uses: ynput/github-data@main
          with:
            repo: "ynput/ayon-addon-action-testing"
            date: "2024-08-20T12:03:23Z"
            query_parameters: "body,labels,title"

        - name: Show results
          run: |
            echo "RAW-response: " && '${{ steps.test-action.outputs.raw-output }}'
            echo "Labels: " && '${{ steps.test-action.outputs.label-list }}'
            echo "Bump-increment: " && '${{ steps.test-action.outputs.label-list }}'
            echo "Changelog: " && '${{ steps.test-action.outputs.changelog-markdown }}' 